import { ListItemProps, ListProps } from '../types';
import { defaultGivers } from './list-givers';
import { defaultProfile } from './user-profile';

export const defaultListItems: ListItemProps[] = [
  {
    title: 'Item 1',
    type: 'item',
    description: 'This is a test description of a wishlist item',
    link: '/',
    bank_account_number: '',
    bank_name: '',
    image: '',
    profile_bank: false,
    list_item_givers: defaultGivers,
  },
  {
    title: 'Item 2',
    type: 'item',
    description: 'This is a test description of a wishlist item',
    link: '/',
    bank_account_number: '',
    bank_name: '',
    image: '',
    profile_bank: false,
    list_item_givers: defaultGivers,
  },
  {
    title: 'Item 3',
    type: 'item',
    description: 'This is a test description of a wishlist item',
    link: '/',
    bank_account_number: '',
    bank_name: '',
    image: '',
    profile_bank: false,
    list_item_givers: defaultGivers,
  },
  {
    title: 'Item 4',
    type: 'item',
    description: 'This is a test description of a wishlist item',
    link: '/',
    bank_account_number: '',
    bank_name: '',
    image: '',
    profile_bank: false,
    list_item_givers: defaultGivers,
  },
  {
    title: 'Item 5',
    type: 'item',
    description: 'This is a test description of a wishlist item',
    link: '/',
    bank_account_number: '',
    bank_name: '',
    image: '',
    profile_bank: false,
    list_item_givers: defaultGivers,
  },
];

export const defaultLists: ListProps[] = [
  {
    owner: defaultProfile,
    title: 'List 1',
    description: 'This is a test description of a wishlist',
    link: '/',
    date: new Date().toString(),
    event_type: 'Birthday',
    image: '',
    listItems: defaultListItems,
    published: false,
    givers: {
      checked: 20,
      secret_checked: 5,
      size: 20,
    },
  },
  {
    owner: defaultProfile,
    title: 'List 2',
    description: 'This is a test description of a wishlist',
    link: '/',
    date: new Date().toString(),
    event_type: 'Birthday',
    image: '',
    listItems: defaultListItems,
    published: false,
    givers: {
      checked: 22,
      secret_checked: 2,
      size: 30,
    },
  },
  {
    owner: defaultProfile,
    title: 'List 3',
    description: 'This is a test description of a wishlist',
    link: '/',
    date: new Date().toString(),
    event_type: 'Birthday',
    image: '',
    listItems: defaultListItems,
    published: true,
    givers: {
      checked: 12,
      secret_checked: 6,
      size: 25,
    },
  },
  {
    owner: defaultProfile,
    title: 'List 4',
    description: 'This is a test description of a wishlist',
    link: '/',
    date: new Date().toString(),
    event_type: 'Birthday',
    image: '',
    listItems: defaultListItems,
    published: false,
    givers: {
      checked: 4,
      secret_checked: 1,
      size: 40,
    },
  },
  {
    owner: defaultProfile,
    title: 'List 5',
    description: 'This is a test description of a wishlist',
    link: '/',
    date: new Date().toString(),
    event_type: 'Birthday',
    image: '',
    listItems: defaultListItems,
    published: true,
    givers: {
      checked: 2,
      secret_checked: 1,
      size: 10,
    },
  },
];
